### PR TITLE
docs(samples): fix drive example stdout upload progress

### PR DESCRIPTION
**Pull request by jorisre**
👋🏻  Hi ! 
Minor fix in Google Drive upload sample.
stdout upload progress wasn't display well ⬇️ 
Screen Shot 2020-10-12 at 19 45 34

***

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/google-api-nodejs-client/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by jorisre** [comment]
@googlebot I signed it!

**Comment by bcoe** [comment]
@jorisre may I ask what shell you are using? I believe in `bash`, this will result in a single line that gets updated with the upload percentage, this might not work in some terminals.

**Comment by jorisre** [comment]
> @jorisre may I ask what shell you are using? I believe in `bash`, this will result in a single line that gets updated with the upload percentage, this might not work in some terminals.

Hi @bcoe 
I use zsh

According to the ReadLine doc, args are required for [clearLine](https://nodejs.org/api/readline.html#readline_readline_clearline_stream_dir_callback) & [cursorTo](https://nodejs.org/api/readline.html#readline_readline_cursorto_stream_x_y_callback)

I got a TS error without args:
Screen Shot 2020-10-15 at 11 16 54

These args are used in [youtube example sample](https://github.com/googleapis/google-api-nodejs-client/blob/bd0accce744ddd55abdd400efbe2bccd96dc6cdf/samples/youtube/upload.js#L64)

**Comment by bcoe** [comment]
@jorisre my bad, I saw the deleted lines, but not that you were simply adding a new parameter.

This looks good to me.

**Review by JustinBeckwith — APPROVED** [review]

**Pull request merged**
